#!/usr/bin/env python3
"""Extract the vocabulary dataset from WordSmart_Vocabulary_List-v18.xlsx
into app/data/vocab.js (a plain <script>-loadable global) and app/data/vocab.json.

The workbook has a single sheet "Vocabulary":
  Group | Word | Bengali Meaning | English Meaning | Synonyms | Antonyms | Example Sentence
with 1200 rows = 12 word lists x 10 groups x 10 words.

No third-party dependencies: xlsx is a zip of XML parts.
"""
import json
import os
import re
import zipfile
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XLSX = os.path.join(ROOT, "WordSmart_Vocabulary_List-v18.xlsx")
OUT_JS = os.path.join(ROOT, "app", "data", "vocab.js")
OUT_JSON = os.path.join(ROOT, "app", "data", "vocab.json")

NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"


def load_rows(path):
    z = zipfile.ZipFile(path)
    ss_root = ET.fromstring(z.read("xl/sharedStrings.xml"))
    strings = [
        "".join(t.text or "" for t in si.iter(NS + "t"))
        for si in ss_root.findall(NS + "si")
    ]
    sheet = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    rows = []
    for row in sheet.find(NS + "sheetData").findall(NS + "row"):
        cells = {}
        for c in row.findall(NS + "c"):
            col = re.match(r"[A-Z]+", c.get("r")).group()
            t = c.get("t")
            v = c.find(NS + "v")
            if t == "s" and v is not None:
                val = strings[int(v.text)]
            elif t == "inlineStr":
                isv = c.find(NS + "is")
                val = "".join(x.text or "" for x in isv.iter(NS + "t")) if isv is not None else ""
            elif v is not None:
                val = v.text or ""
            else:
                val = ""
            cells[col] = (val or "").strip()
        rows.append((int(row.get("r")), cells))
    return rows


def clean_split(text):
    parts = [p.strip() for p in re.split(r"[,;]", text or "")]
    return [p for p in parts if p]


def main():
    rows = load_rows(XLSX)
    records = [cells for rn, cells in rows if rn > 1 and cells.get("B")]

    lists = {}          # list_no -> {"groups": {group_no: [words]}}
    words = {}          # word id -> entry
    for rec in records:
        m = re.match(r"List\s*(\d+)\s*-\s*Group\s*(\d+)", rec.get("A", ""))
        if not m:
            raise SystemExit("Unparsed group cell: %r" % rec.get("A"))
        list_no, group_no = int(m.group(1)), int(m.group(2))
        word = rec["B"]
        groups = lists.setdefault(list_no, {"groups": {}})["groups"].setdefault(group_no, [])
        wid = "w%02d%02d%02d" % (list_no, group_no, len(groups) + 1)
        entry = {
            "id": wid,
            "w": word,
            "bn": rec.get("C", ""),
            "en": rec.get("D", ""),
            "syn": clean_split(rec.get("E", "")),
            "ant": clean_split(rec.get("F", "")),
            "ex": rec.get("G", ""),
            "l": list_no,
            "g": group_no,
        }
        words[wid] = entry
        lists[list_no]["groups"][group_no].append(wid)

    # sanity checks
    assert len(lists) == 12, "expected 12 lists, got %d" % len(lists)
    for lno, lob in lists.items():
        assert len(lob["groups"]) == 10, "list %s has %d groups" % (lno, len(lob["groups"]))
        for gno, ids in lob["groups"].items():
            assert len(ids) == 10, "list %s group %s has %d words" % (lno, gno, len(ids))
    assert len(words) == 1200, len(words)

    data = {
        "app": "Vocab Ledger",
        "source": "WordSmart_Vocabulary_List-v18.xlsx",
        "listCount": 12,
        "groupsPerList": 10,
        "wordsPerGroup": 10,
        "lists": [
            {
                "no": lno,
                "title": "Word List %d" % lno,
                "groups": [
                    {"no": gno, "title": "Group %d" % gno, "words": lists[lno]["groups"][gno]}
                    for gno in sorted(lists[lno]["groups"])
                ],
            }
            for lno in sorted(lists)
        ],
        "words": words,
    }

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    js = "// Generated by tools/build_vocab.py - do not edit by hand.\n"
    js += "window.VOCAB = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(js)
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False)
    print("wrote %s (%d bytes)" % (OUT_JS, os.path.getsize(OUT_JS)))
    print("wrote %s (%d bytes)" % (OUT_JSON, os.path.getsize(OUT_JSON)))


if __name__ == "__main__":
    main()
